### ISSUE TITLE
ui-jobs  &  ui-webs fails to start 

### ISSUE THREAD

**Issue by raviprasad239** [Juniper/contrail-installer#131]
ui-jobs  &  ui-webs are failed to start, looks like redis-server is also not running : 
log from contrail-status:

----------------------------------------------------------------
----------------------------------------------------------------
ui-jobs              : ERROR
----------------------------------------------------------------
l/contrail-installer/status/contrail/ui-jobs.failure"start" | tee "/home/contrai b-core;
[1] 24311
sudo node jobServerStart.js

module.js:340
    throw err;
          ^
Error: Cannot find module 'redis'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at Object.<anonymous> (/opt/stack/contrail/contrail-web-core/src/serverroot/utils/redis.utils.js:5:13)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:362:17)
ui-jobs failed to start
contrail@ubuntu1:/opt/stack/contrail/contrail-web-core$
----------------------------------------------------------------
----------------------------------------------------------------
ui-webs              : ERROR
----------------------------------------------------------------
l/contrail-installer/status/contrail/ui-webs.failure"start" | tee "/home/contrai b-core;
[1] 24409
sudo node webServerStart.js

module.js:340
    throw err;
          ^
Error: Cannot find module 'redis'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at Object.<anonymous> (/opt/stack/contrail/contrail-web-core/src/serverroot/utils/redis.utils.js:5:13)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:362:17)
ui-webs failed to start
contrail@ubuntu1:/opt/stack/contrail/contrail-web-core$

**Comment by DaireNiC** [comment]
I am having the same issue on Fedora 20. Any solution?

**Comment by biswajit-mandal** [comment]
Please check the system where you are running, nodejs is installed or not, please do $node --version
