### ISSUE TITLE
Failure creating NET_ID for private f5eb0aa2789e4d8091d41af66b092748

### ISSUE THREAD

**Issue by amandeepsingh91** [Juniper/contrail-installer#155]
In Single Node (Openstack Ocata + Opencontrail) i'm getting Error : Failure creating NET_ID for private

I have Added opencontrail plugin into localrc

Copied as : 

cp  ~/contrail-installer/devstack/lib/neutron_plugins/opencontrail lib/neutron_plugins/opencontrail

cp ~/contrail-installer/devstack/samples/localrc-all ~/devstack/localrc

after running ./stack.sh  i am getting : 

/home/stack/devstack/functions-common:211 Failure creating NET_ID for private f5eb0aa2789e4d8091d41af66b092748

**logs**

017-09-15 13:02:31.108 INFO neutron.wsgi [-] 192.168.56.106 - - [15/Sep/2017 13:02:31] "GET / HTTP/1.1" 200 271 0.000528
2017-09-15 13:02:31.151 DEBUG neutron.api.v2.base [req-576fa389-b9b4-4c32-b102-8bb46f751483 admin admin] Request body: {u'network': {u'project_id': u'f5eb0aa2789e4d8091d41af66b092748', u'name': u'private', u'admin_state_up': True}} from (pid=7541) prepare_request_body /opt/stack/neutron/neutron/api/v2/base.py:698
2017-09-15 13:02:31.151 WARNING neutron.quota [req-576fa389-b9b4-4c32-b102-8bb46f751483 admin admin] Deprecated: The quota driver neutron.quota.ConfDriver is deprecated as of Liberty. neutron.db.quota.driver.DbQuotaDriver should be used in its place
2017-09-15 13:02:31.152 INFO neutron.quota [req-576fa389-b9b4-4c32-b102-8bb46f751483 admin admin] Loaded quota_driver: <neutron.quota.ConfDriver object at 0x7f0f51e45190>.
2017-09-15 13:02:31.154 ERROR neutron.api.v2.resource [req-576fa389-b9b4-4c32-b102-8bb46f751483 admin admin] create failed: No details.
2017-09-15 13:02:31.154 TRACE neutron.api.v2.resource Traceback (most recent call last):
2017-09-15 13:02:31.154 TRACE neutron.api.v2.resource   File "/opt/stack/neutron/neutron/api/v2/resource.py", line 93, in resource
2017-09-15 13:02:31.154 TRACE neutron.api.v2.resource     result = method(request=request, **args)
2017-09-15 13:02:31.154 TRACE neutron.api.v2.resource   File "/opt/stack/neutron/neutron/api/v2/base.py", line 437, in create
2017-09-15 13:02:31.154 TRACE neutron.api.v2.resource     return self._create(request, body, **kwargs)
2017-09-15 13:02:31.154 TRACE neutron.api.v2.resource   File "/opt/stack/neutron/neutron/db/api.py", line 95, in wrapped
2017-09-15 13:02:31.154 TRACE neutron.api.v2.resource     setattr(e, '_RETRY_EXCEEDED', True)
2017-09-15 13:02:31.154 TRACE neutron.api.v2.resource   File "/usr/local/lib/python2.7/dist-packages/oslo_utils/excutils.py", line 220, in __exit__
2017-09-15 13:02:31.154 TRACE neutron.api.v2.resource     self.force_reraise()
2017-09-15 13:02:31.154 TRACE neutron.api.v2.resource   File "/usr/local/lib/python2.7/dist-packages/oslo_utils/excutils.py", line 196, in force_reraise
2017-09-15 13:02:31.154 TRACE neutron.api.v2.resource     six.reraise(self.type_, self.value, self.tb)
2017-09-15 13:02:31.154 TRACE neutron.api.v2.resource   File "/opt/stack/neutron/neutron/db/api.py", line 91, in wrapped
2017-09-15 13:02:31.154 TRACE neutron.api.v2.resource     return f(*args, **kwargs)
2017-09-15 13:02:31.154 TRACE neutron.api.v2.resource   File "/usr/local/lib/python2.7/dist-packages/oslo_db/api.py", line 151, in wrapper
2017-09-15 13:02:31.154 TRACE neutron.api.v2.resource     ectxt.value = e.inner_exc
2017-09-15 13:02:31.154 TRACE neutron.api.v2.resource   File "/usr/local/lib/python2.7/dist-packages/oslo_utils/excutils.py", line 220, in __exit__
2017-09-15 13:02:31.154 TRACE neutron.api.v2.resource     self.force_reraise()
2017-09-15 13:02:31.154 TRACE neutron.api.v2.resource   File "/usr/local/lib/python2.7/dist-packages/oslo_utils/excutils.py", line 196, in force_reraise
2017-09-15 13:02:31.154 TRACE neutron.api.v2.resource     six.reraise(self.type_, self.value, self.tb)
2017-09-15 13:02:31.154 TRACE neutron.api.v2.resource   File "/usr/local/lib/python2.7/dist-packages/oslo_db/api.py", line 139, in wrapper
2017-09-15 13:02:31.154 TRACE neutron.api.v2.resource     return f(*args, **kwargs)
2017-09-15 13:02:31.154 TRACE neutron.api.v2.resource   File "/opt/stack/neutron/neutron/db/api.py", line 131, in wrapped
2017-09-15 13:02:31.154 TRACE neutron.api.v2.resource     traceback.format_exc())
2017-09-15 13:02:31.154 TRACE neutron.api.v2.resource   File "/usr/local/lib/python2.7/dist-packages/oslo_utils/excutils.py", line 220, in __exit__
2017-09-15 13:02:31.154 TRACE neutron.api.v2.resource     self.force_reraise()
2017-09-15 13:02:31.154 TRACE neutron.api.v2.resource   File "/usr/local/lib/python2.7/dist-packages/oslo_utils/excutils.py", line 196, in force_reraise
2017-09-15 13:02:31.154 TRACE neutron.api.v2.resource     six.reraise(self.type_, self.value, self.tb)
2017-09-15 13:02:31.154 TRACE neutron.api.v2.resource   File "/opt/stack/neutron/neutron/db/api.py", line 126, in wrapped
2017-09-15 13:02:31.154 TRACE neutron.api.v2.resource     return f(*dup_args, **dup_kwargs)
2017-09-15 13:02:31.154 TRACE neutron.api.v2.resource   File "/opt/stack/neutron/neutron/api/v2/base.py", line 481, in _create
2017-09-15 13:02:31.154 TRACE neutron.api.v2.resource     self._plugin)
2017-09-15 13:02:31.154 TRACE neutron.api.v2.resource   File "/opt/stack/neutron/neutron/quota/__init__.py", line 234, in make_reservation
2017-09-15 13:02:31.154 TRACE neutron.api.v2.resource     plugin)
2017-09-15 13:02:31.154 TRACE neutron.api.v2.resource   File "/opt/stack/neutron/neutron/quota/__init__.py", line 133, in make_reservation
2017-09-15 13:02:31.154 TRACE neutron.api.v2.resource     count = QUOTAS.count(context, resource, plugin, tenant_id)
2017-09-15 13:02:31.154 TRACE neutron.api.v2.resource   File "/opt/stack/neutron/neutron/quota/__init__.py", line 207, in count
2017-09-15 13:02:31.154 TRACE neutron.api.v2.resource     return res.count(context, *args, **kwargs)
2017-09-15 13:02:31.154 TRACE neutron.api.v2.resource   File "/opt/stack/neutron/neutron/quota/resource.py", line 133, in count
2017-09-15 13:02:31.154 TRACE neutron.api.v2.resource     return self._count_func(context, plugin, self.plural_name, tenant_id)
2017-09-15 13:02:31.154 TRACE neutron.api.v2.resource   File "/opt/stack/neutron/neutron/quota/resource.py", line 37, in _count_resource
2017-09-15 13:02:31.154 TRACE neutron.api.v2.resource     return obj_count_getter(context, filters={'tenant_id': [tenant_id]})
2017-09-15 13:02:31.154 TRACE neutron.api.v2.resource   File "/opt/stack/contrail/openstack/neutron_plugin/neutron_plugin_contrail/plugins/opencontrail/contrail_plugin_base.py", line 252, in get_networks_count
2017-09-15 13:02:31.154 TRACE neutron.api.v2.resource     networks_count = self._count_resource('network', context, filters)
2017-09-15 13:02:31.154 TRACE neutron.api.v2.resource   File "/opt/stack/contrail/openstack/neutron_plugin/neutron_plugin_contrail/plugins/opencontrail/contrail_plugin.py", line 345, in _count_resource
2017-09-15 13:02:31.154 TRACE neutron.api.v2.resource     res_type, 'READCOUNT')
2017-09-15 13:02:31.154 TRACE neutron.api.v2.resource   File "/opt/stack/contrail/openstack/neutron_plugin/neutron_plugin_contrail/plugins/opencontrail/contrail_plugin.py", line 206, in _request_backend
2017-09-15 13:02:31.154 TRACE neutron.api.v2.resource     response = self._relay_request(url_path, data=data)
2017-09-15 13:02:31.154 TRACE neutron.api.v2.resource   File "/opt/stack/contrail/openstack/neutron_plugin/neutron_plugin_contrail/plugins/opencontrail/contrail_plugin.py", line 199, in _relay_request
2017-09-15 13:02:31.154 TRACE neutron.api.v2.resource     url, data=data, headers={'Content-type': 'application/json'})
2017-09-15 13:02:31.154 TRACE neutron.api.v2.resource   File "/opt/stack/contrail/openstack/neutron_plugin/neutron_plugin_contrail/plugins/opencontrail/contrail_plugin.py", line 187, in _request_api_server_authn
2017-09-15 13:02:31.154 TRACE neutron.api.v2.resource     response = self._request_api_server(url, data, headers=authn_headers)
2017-09-15 13:02:31.154 TRACE neutron.api.v2.resource   File "/opt/stack/contrail/openstack/neutron_plugin/neutron_plugin_contrail/plugins/opencontrail/contrail_plugin.py", line 150, in _request_api_server
2017-09-15 13:02:31.154 TRACE neutron.api.v2.resource     response = requests.post(url, data=data, headers=headers)
2017-09-15 13:02:31.154 TRACE neutron.api.v2.resource   File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 110, in post
2017-09-15 13:02:31.154 TRACE neutron.api.v2.resource     return request('post', url, data=data, json=json, **kwargs)
2017-09-15 13:02:31.154 TRACE neutron.api.v2.resource   File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 56, in request
2017-09-15 13:02:31.154 TRACE neutron.api.v2.resource     return session.request(method=method, url=url, **kwargs)
2017-09-15 13:02:31.154 TRACE neutron.api.v2.resource   File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 488, in request
2017-09-15 13:02:31.154 TRACE neutron.api.v2.resource     resp = self.send(prep, **send_kwargs)
2017-09-15 13:02:31.154 TRACE neutron.api.v2.resource   File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 609, in send
2017-09-15 13:02:31.154 TRACE neutron.api.v2.resource     r = adapter.send(request, **kwargs)
2017-09-15 13:02:31.154 TRACE neutron.api.v2.resource   File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 487, in send
2017-09-15 13:02:31.154 TRACE neutron.api.v2.resource     raise ConnectionError(e, request=request)
2017-09-15 13:02:31.154 TRACE neutron.api.v2.resource ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8082): Max retries exceeded with url: /neutron/network (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f0f51e45ad0>: Failed to establish a new connection: [Errno 111] ECONNREFUSED',))
2017-09-15 13:02:31.154 TRACE neutron.api.v2.resource 
2017-09-15 13:02:31.252 INFO neutron.wsgi [req-576fa389-b9b4-4c32-b102-8bb46f751483 admin admin] 192.168.56.106 - - [15/Sep/2017 13:02:31] "POST /v2.0/networks HTTP/1.1" 500 368 0.140965

2017-09-15 12:27:16.173 TRACE neutron.common.utils     (self.namespace, name))
2017-09-15 12:27:16.173 TRACE neutron.common.utils NoMatches: No 'neutron.core_plugins' driver found, looking for 'neutron_plugin_contrail.plugins.opencontrail.contrail_plugin_v3.NeutronPluginContrailCoreV3'
2017-09-15 12:27:16.173 TRACE neutron.common.utils 
2017-09-15 12:27:16.200 ERROR neutron.common.utils [-] Error loading class by class name
2017-09-15 12:27:16.200 TRACE neutron.common.utils Traceback (most recent call last):
2017-09-15 12:27:16.200 TRACE neutron.common.utils   File "/opt/stack/neutron/neutron/common/utils.py", line 425, in load_class_by_alias_or_classname
2017-09-15 12:27:16.200 TRACE neutron.common.utils     class_to_load = importutils.import_class(name)
2017-09-15 12:27:16.200 TRACE neutron.common.utils   File "/usr/local/lib/python2.7/dist-packages/oslo_utils/importutils.py", line 30, in import_class
2017-09-15 12:27:16.200 TRACE neutron.common.utils     __import__(mod_str)
2017-09-15 12:27:16.200 TRACE neutron.common.utils ImportError: No module named neutron_plugin_contrail.plugins.opencontrail.contrail_plugin_v3
2017-09-15 12:27:16.200 TRACE neutron.common.utils 
2017-09-15 12:27:16.217 ERROR neutron.manager [-] Plugin 'neutron_plugin_contrail.plugins.opencontrail.contrail_plugin_v3.NeutronPluginContrailCoreV3' not found.
2017-09-15 12:27:16.218 DEBUG oslo_concurrency.lockutils [-] Lock "manager" released by "neutron.manager._create_instance" :: held 0.045s from (pid=30221) inner /usr/local/lib/python2.7/dist-packages/oslo_concurrency/lockutils.py:282
2017-09-15 12:27:16.218 ERROR neutron.service [-] Unrecoverable error: please check log for details.
2017-09-15 12:27:16.218 TRACE neutron.service Traceback (most recent call last):
2017-09-15 12:27:16.218 TRACE neutron.service   File "/opt/stack/neutron/neutron/service.py", line 87, in serve_wsgi
2017-09-15 12:27:16.218 TRACE neutron.service     service.start()
2017-09-15 12:27:16.218 TRACE neutron.service   File "/opt/stack/neutron/neutron/service.py", line 63, in start
2017-09-15 12:27:16.218 TRACE neutron.service     self.wsgi_app = _run_wsgi(self.app_name)
2017-09-15 12:27:16.218 TRACE neutron.service   File "/opt/stack/neutron/neutron/service.py", line 288, in _run_wsgi
2017-09-15 12:27:16.218 TRACE neutron.service     app = config.load_paste_app(app_name)
2017-09-15 12:27:16.218 TRACE neutron.service   File "/opt/stack/neutron/neutron/common/config.py", line 133, in load_paste_app
2017-09-15 12:27:16.218 TRACE neutron.service     app = loader.load_app(app_name)
2017-09-15 12:27:16.218 TRACE neutron.service   File "/usr/local/lib/python2.7/dist-packages/oslo_service/wsgi.py", line 353, in load_app
2017-09-15 12:27:16.218 TRACE neutron.service     return deploy.loadapp("config:%s" % self.config_path, name=name)
2017-09-15 12:27:16.218 TRACE neutron.service   File "/usr/local/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py", line 247, in loadapp
2017-09-15 12:27:16.218 TRACE neutron.service     return loadobj(APP, uri, name=name, **kw)
2017-09-15 12:27:16.218 TRACE neutron.service   File "/usr/local/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py", line 272, in loadobj
2017-09-15 12:27:16.218 TRACE neutron.service     return context.create()
2017-09-15 12:27:16.218 TRACE neutron.service   File "/usr/local/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py", line 710, in create
2017-09-15 12:27:16.218 TRACE neutron.service     return self.object_type.invoke(self)
2017-09-15 12:27:16.218 TRACE neutron.service   File "/usr/local/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py", line 144, in invoke
2017-09-15 12:27:16.218 TRACE neutron.service     **context.local_conf)
2017-09-15 12:27:16.218 TRACE neutron.service   File "/usr/local/lib/python2.7/dist-packages/paste/deploy/util.py", line 55, in fix_call
2017-09-15 12:27:16.218 TRACE neutron.service     val = callable(*args, **kw)
2017-09-15 12:27:16.218 TRACE neutron.service   File "/usr/local/lib/python2.7/dist-packages/paste/urlmap.py", line 31, in urlmap_factory
2017-09-15 12:27:16.218 TRACE neutron.service     app = loader.get_app(app_name, global_conf=global_conf)
2017-09-15 12:27:16.218 TRACE neutron.service   File "/usr/local/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py", line 350, in get_app
2017-09-15 12:27:16.218 TRACE neutron.service     name=name, global_conf=global_conf).create()
2017-09-15 12:27:16.218 TRACE neutron.service   File "/usr/local/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py", line 710, in create
2017-09-15 12:27:16.218 TRACE neutron.service     return self.object_type.invoke(self)
2017-09-15 12:27:16.218 TRACE neutron.service   File "/usr/local/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py", line 144, in invoke
2017-09-15 12:27:16.218 TRACE neutron.service     **context.local_conf)
2017-09-15 12:27:16.218 TRACE neutron.service   File "/usr/local/lib/python2.7/dist-packages/paste/deploy/util.py", line 55, in fix_call
2017-09-15 12:27:16.218 TRACE neutron.service     val = callable(*args, **kw)
2017-09-15 12:27:16.218 TRACE neutron.service   File "/opt/stack/neutron/neutron/auth.py", line 71, in pipeline_factory
2017-09-15 12:27:16.218 TRACE neutron.service     app = loader.get_app(pipeline[-1])
2017-09-15 12:27:16.218 TRACE neutron.service   File "/usr/local/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py", line 350, in get_app
2017-09-15 12:27:16.218 TRACE neutron.service     name=name, global_conf=global_conf).create()
2017-09-15 12:27:16.218 TRACE neutron.service   File "/usr/local/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py", line 710, in create
2017-09-15 12:27:16.218 TRACE neutron.service     return self.object_type.invoke(self)
2017-09-15 12:27:16.218 TRACE neutron.service   File "/usr/local/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py", line 146, in invoke
2017-09-15 12:27:16.218 TRACE neutron.service     return fix_call(context.object, context.global_conf, **context.local_conf)
2017-09-15 12:27:16.218 TRACE neutron.service   File "/usr/local/lib/python2.7/dist-packages/paste/deploy/util.py", line 55, in fix_call
2017-09-15 12:27:16.218 TRACE neutron.service     val = callable(*args, **kw)
2017-09-15 12:27:16.218 TRACE neutron.service   File "/opt/stack/neutron/neutron/api/v2/router.py", line 73, in factory
2017-09-15 12:27:16.218 TRACE neutron.service     return cls(**local_config)
2017-09-15 12:27:16.218 TRACE neutron.service   File "/opt/stack/neutron/neutron/api/v2/router.py", line 77, in __init__
2017-09-15 12:27:16.218 TRACE neutron.service     manager.init()
2017-09-15 12:27:16.218 TRACE neutron.service   File "/opt/stack/neutron/neutron/manager.py", line 291, in init
2017-09-15 12:27:16.218 TRACE neutron.service     NeutronManager.get_instance()
2017-09-15 12:27:16.218 TRACE neutron.service   File "/opt/stack/neutron/neutron/manager.py", line 241, in get_instance
2017-09-15 12:27:16.218 TRACE neutron.service     cls._create_instance()
2017-09-15 12:27:16.218 TRACE neutron.service   File "/usr/local/lib/python2.7/dist-packages/oslo_concurrency/lockutils.py", line 271, in inner
2017-09-15 12:27:16.218 TRACE neutron.service     return f(*args, **kwargs)
2017-09-15 12:27:16.218 TRACE neutron.service   File "/opt/stack/neutron/neutron/manager.py", line 227, in _create_instance
2017-09-15 12:27:16.218 TRACE neutron.service     cls._instance = cls()
2017-09-15 12:27:16.218 TRACE neutron.service   File "/opt/stack/neutron/neutron/manager.py", line 131, in __init__
2017-09-15 12:27:16.218 TRACE neutron.service     plugin_provider)
2017-09-15 12:27:16.218 TRACE neutron.service   File "/opt/stack/neutron/neutron/manager.py", line 163, in _get_plugin_instance
2017-09-15 12:27:16.218 TRACE neutron.service     plugin_class = self.load_class_for_provider(namespace, plugin_provider)
2017-09-15 12:27:16.218 TRACE neutron.service   File "/opt/stack/neutron/neutron/manager.py", line 160, in load_class_for_provider
2017-09-15 12:27:16.218 TRACE neutron.service     LOG.error(_LE("Plugin '%s' not found."), plugin_provider)
2017-09-15 12:27:16.218 TRACE neutron.service   File "/usr/local/lib/python2.7/dist-packages/oslo_utils/excutils.py", line 220, in __exit__
2017-09-15 12:27:16.218 TRACE neutron.service     self.force_reraise()
2017-09-15 12:27:16.218 TRACE neutron.service   File "/usr/local/lib/python2.7/dist-packages/oslo_utils/excutils.py", line 196, in force_reraise
2017-09-15 12:27:16.218 TRACE neutron.service     six.reraise(self.type_, self.value, self.tb)
2017-09-15 12:27:16.218 TRACE neutron.service   File "/opt/stack/neutron/neutron/manager.py", line 157, in load_class_for_provider
2017-09-15 12:27:16.218 TRACE neutron.service     plugin_provider)
2017-09-15 12:27:16.218 TRACE neutron.service   File "/opt/stack/neutron/neutron/common/utils.py", line 431, in load_class_by_alias_or_classname
2017-09-15 12:27:16.218 TRACE neutron.service     raise ImportError(_("Class not found."))
2017-09-15 12:27:16.218 TRACE neutron.service ImportError: Class not found.
2017-09-15 12:27:16.218 TRACE neutron.service 
2017-09-15 12:27:16.265 CRITICAL neutron [-] ImportError: Class not found.

2017-09-15 12:27:16.265 TRACE neutron Traceback (most recent call last):
2017-09-15 12:27:16.265 TRACE neutron   File "/usr/local/bin/neutron-server", line 10, in <module>
2017-09-15 12:27:16.265 TRACE neutron     sys.exit(main())
2017-09-15 12:27:16.265 TRACE neutron   File "/opt/stack/neutron/neutron/cmd/eventlet/server/__init__.py", line 22, in main
2017-09-15 12:27:16.265 TRACE neutron     server.boot_server(_main_neutron_server)
2017-09-15 12:27:16.265 TRACE neutron   File "/opt/stack/neutron/neutron/server/__init__.py", line 37, in boot_server
2017-09-15 12:27:16.265 TRACE neutron     server_func()
2017-09-15 12:27:16.265 TRACE neutron   File "/opt/stack/neutron/neutron/cmd/eventlet/server/__init__.py", line 27, in _main_neutron_server
2017-09-15 12:27:16.265 TRACE neutron     wsgi_eventlet.eventlet_wsgi_server()
2017-09-15 12:27:16.265 TRACE neutron   File "/opt/stack/neutron/neutron/server/wsgi_eventlet.py", line 25, in eventlet_wsgi_server
2017-09-15 12:27:16.265 TRACE neutron     neutron_api = service.serve_wsgi(service.NeutronApiService)
2017-09-15 12:27:16.265 TRACE neutron   File "/opt/stack/neutron/neutron/service.py", line 90, in serve_wsgi
2017-09-15 12:27:16.265 TRACE neutron     LOG.exception(_LE('Unrecoverable error: please check log '
2017-09-15 12:27:16.265 TRACE neutron   File "/usr/local/lib/python2.7/dist-packages/oslo_utils/excutils.py", line 220, in __exit__
2017-09-15 12:27:16.265 TRACE neutron     self.force_reraise()
2017-09-15 12:27:16.265 TRACE neutron   File "/usr/local/lib/python2.7/dist-packages/oslo_utils/excutils.py", line 196, in force_reraise
2017-09-15 12:27:16.265 TRACE neutron     six.reraise(self.type_, self.value, self.tb)
2017-09-15 12:27:16.265 TRACE neutron   File "/opt/stack/neutron/neutron/service.py", line 87, in serve_wsgi
2017-09-15 12:27:16.265 TRACE neutron     service.start()
2017-09-15 12:27:16.265 TRACE neutron   File "/opt/stack/neutron/neutron/service.py", line 63, in start
2017-09-15 12:27:16.265 TRACE neutron     self.wsgi_app = _run_wsgi(self.app_name)
2017-09-15 12:27:16.265 TRACE neutron   File "/opt/stack/neutron/neutron/service.py", line 288, in _run_wsgi
2017-09-15 12:27:16.265 TRACE neutron     app = config.load_paste_app(app_name)
2017-09-15 12:27:16.265 TRACE neutron   File "/opt/stack/neutron/neutron/common/config.py", line 133, in load_paste_app
2017-09-15 12:27:16.265 TRACE neutron     app = loader.load_app(app_name)
2017-09-15 12:27:16.265 TRACE neutron   File "/usr/local/lib/python2.7/dist-packages/oslo_service/wsgi.py", line 353, in load_app
2017-09-15 12:27:16.265 TRACE neutron     return deploy.loadapp("config:%s" % self.config_path, name=name)
2017-09-15 12:27:16.265 TRACE neutron   File "/usr/local/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py", line 247, in loadapp
2017-09-15 12:27:16.265 TRACE neutron     return loadobj(APP, uri, name=name, **kw)
2017-09-15 12:27:16.265 TRACE neutron   File "/usr/local/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py", line 272, in loadobj
2017-09-15 12:27:16.265 TRACE neutron     return context.create()
2017-09-15 12:27:16.265 TRACE neutron   File "/usr/local/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py", line 710, in create
2017-09-15 12:27:16.265 TRACE neutron     return self.object_type.invoke(self)
2017-09-15 12:27:16.265 TRACE neutron   File "/usr/local/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py", line 144, in invoke
2017-09-15 12:27:16.265 TRACE neutron     **context.local_conf)
2017-09-15 12:27:16.265 TRACE neutron   File "/usr/local/lib/python2.7/dist-packages/paste/deploy/util.py", line 55, in fix_call
2017-09-15 12:27:16.265 TRACE neutron     val = callable(*args, **kw)
2017-09-15 12:27:16.265 TRACE neutron   File "/usr/local/lib/python2.7/dist-packages/paste/urlmap.py", line 31, in urlmap_factory
2017-09-15 12:27:16.265 TRACE neutron     app = loader.get_app(app_name, global_conf=global_conf)
2017-09-15 12:27:16.265 TRACE neutron   File "/usr/local/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py", line 350, in get_app
2017-09-15 12:27:16.265 TRACE neutron     name=name, global_conf=global_conf).create()
2017-09-15 12:27:16.265 TRACE neutron   File "/usr/local/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py", line 710, in create
2017-09-15 12:27:16.265 TRACE neutron     return self.object_type.invoke(self)
2017-09-15 12:27:16.265 TRACE neutron   File "/usr/local/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py", line 144, in invoke
2017-09-15 12:27:16.265 TRACE neutron     **context.local_conf)
2017-09-15 12:27:16.265 TRACE neutron   File "/usr/local/lib/python2.7/dist-packages/paste/deploy/util.py", line 55, in fix_call
2017-09-15 12:27:16.265 TRACE neutron     val = callable(*args, **kw)
2017-09-15 12:27:16.265 TRACE neutron   File "/opt/stack/neutron/neutron/auth.py", line 71, in pipeline_factory
2017-09-15 12:27:16.265 TRACE neutron     app = loader.get_app(pipeline[-1])
2017-09-15 12:27:16.265 TRACE neutron   File "/usr/local/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py", line 350, in get_app
2017-09-15 12:27:16.265 TRACE neutron     name=name, global_conf=global_conf).create()
2017-09-15 12:27:16.265 TRACE neutron   File "/usr/local/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py", line 710, in create
2017-09-15 12:27:16.265 TRACE neutron     return self.object_type.invoke(self)
2017-09-15 12:27:16.265 TRACE neutron   File "/usr/local/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py", line 146, in invoke
2017-09-15 12:27:16.265 TRACE neutron     return fix_call(context.object, context.global_conf, **context.local_conf)
2017-09-15 12:27:16.265 TRACE neutron   File "/usr/local/lib/python2.7/dist-packages/paste/deploy/util.py", line 55, in fix_call
2017-09-15 12:27:16.265 TRACE neutron     val = callable(*args, **kw)
2017-09-15 12:27:16.265 TRACE neutron   File "/opt/stack/neutron/neutron/api/v2/router.py", line 73, in factory
2017-09-15 12:27:16.265 TRACE neutron     return cls(**local_config)
2017-09-15 12:27:16.265 TRACE neutron   File "/opt/stack/neutron/neutron/api/v2/router.py", line 77, in __init__
2017-09-15 12:27:16.265 TRACE neutron     manager.init()
2017-09-15 12:27:16.265 TRACE neutron   File "/opt/stack/neutron/neutron/manager.py", line 291, in init
2017-09-15 12:27:16.265 TRACE neutron     NeutronManager.get_instance()
2017-09-15 12:27:16.265 TRACE neutron   File "/opt/stack/neutron/neutron/manager.py", line 241, in get_instance
2017-09-15 12:27:16.265 TRACE neutron     cls._create_instance()
2017-09-15 12:27:16.265 TRACE neutron   File "/usr/local/lib/python2.7/dist-packages/oslo_concurrency/lockutils.py", line 271, in inner
2017-09-15 12:27:16.265 TRACE neutron     return f(*args, **kwargs)
2017-09-15 12:27:16.265 TRACE neutron   File "/opt/stack/neutron/neutron/manager.py", line 227, in _create_instance
2017-09-15 12:27:16.265 TRACE neutron     cls._instance = cls()
2017-09-15 12:27:16.265 TRACE neutron   File "/opt/stack/neutron/neutron/manager.py", line 131, in __init__
2017-09-15 12:27:16.265 TRACE neutron     plugin_provider)
2017-09-15 12:27:16.265 TRACE neutron   File "/opt/stack/neutron/neutron/manager.py", line 163, in _get_plugin_instance
2017-09-15 12:27:16.265 TRACE neutron     plugin_class = self.load_class_for_provider(namespace, plugin_provider)
2017-09-15 12:27:16.265 TRACE neutron   File "/opt/stack/neutron/neutron/manager.py", line 160, in load_class_for_provider
2017-09-15 12:27:16.265 TRACE neutron     LOG.error(_LE("Plugin '%s' not found."), plugin_provider)
2017-09-15 12:27:16.265 TRACE neutron   File "/usr/local/lib/python2.7/dist-packages/oslo_utils/excutils.py", line 220, in __exit__
2017-09-15 12:27:16.265 TRACE neutron     self.force_reraise()
2017-09-15 12:27:16.265 TRACE neutron   File "/usr/local/lib/python2.7/dist-packages/oslo_utils/excutils.py", line 196, in force_reraise
2017-09-15 12:27:16.265 TRACE neutron     six.reraise(self.type_, self.value, self.tb)
2017-09-15 12:27:16.265 TRACE neutron   File "/opt/stack/neutron/neutron/manager.py", line 157, in load_class_for_provider
2017-09-15 12:27:16.265 TRACE neutron     plugin_provider)
2017-09-15 12:27:16.265 TRACE neutron   File "/opt/stack/neutron/neutron/common/utils.py", line 431, in load_class_by_alias_or_classname
2017-09-15 12:27:16.265 TRACE neutron     raise ImportError(_("Class not found."))
2017-09-15 12:27:16.265 TRACE neutron ImportError: Class not found.
2017-09-15 12:27:16.265 TRACE neutron 
q-svc failed to start

**Comment by adnaniqbal** [comment]
This could be resolved using following in localrc

NEUTRON_CREATE_INITIAL_NETWORKS=False

**Comment by shubh01012000** [comment]
@amandeepsingh91 Even I'm facing the same issue. Did it get resolved?
@adnaniqbal  I did not understand where to paste that.

**Comment by allaboutopensource** [comment]
you need to edit the local.conf and paste this line.

**Comment by Niceta-Nduku** [comment]
> 

Paste what line?
